version: '3.7'
services:
  app:
    container_name: amati_app
    image: bocahankeren/amati-app:0.9
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    container_name: amati_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: amati

volumes:
  db_data:
